export { cabinetPage } from './cabinet';
export { contactPage } from './contact';
export { expertisesPage } from './expertises';
export { homePage } from './home';
export { journalPage } from './journal';
export { methodePage } from './methode';
export { missionsPage } from './missions';
export { siteRoutes } from './navigation';
export { referencesPage } from './references';
export type { SiteCard, SitePage, SiteSection } from './types';
